{"level":"error","message":"login failed login failed","stack":"Error: login failed\n    at module.exports.login (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\src\\routes\\auth\\controller.js:37:11)\n    at newFn (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at validate (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\src\\routes\\controller.js:27:5)\n    at newFn (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at middleware (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\node_modules\\express-validator\\src\\middlewares\\check.js:16:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"something goes wrong outside of express routes something goes wrong outside of express routes","stack":"Error: something goes wrong outside of express routes\n    at Object.<anonymous> (E:\\learning\\tutorial\\NodeJS\\AUTH-Project\\index.js:30:7)\n    at Module._compile (node:internal/modules/cjs/loader:1256:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)\n    at Module.load (node:internal/modules/cjs/loader:1119:32)\n    at Module._load (node:internal/modules/cjs/loader:960:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
